### Get all contacts 
GET http://localhost:3000/users

### Get contants by IDs
GET http://localhost:3000/users/6542bc9ccc322e8b3af6187f
### Get contants by IDs
GET http://localhost:3000/users/6542bd5dcc322e8b3af61880
### Get contants by IDs
GET http://localhost:3000/users/6542bdbecc322e8b3af61881


### Get All Contacts from normal site 
GET https://cse341-project1-q5zi.onrender.com/users

### Get contants by IDs
GET https://cse341-project1-q5zi.onrender.com/users/6542bdbecc322e8b3af61881



# ### Create Contacts
# POST http://localhost:3000/users HTTP/1.1
# Content-Type: application/json
# {
#     "firstName": "Shawnie",
#     "LastName": "Thorsen",
#     "email": "st@yahoo.com",
#     "favoriteColor": "Yellow",
#     "birthday": "September 24, 1992"
#   }